name: Test Lambda

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  
jobs:
  aws_cdk:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14.15.1"
          
      - name: Install SAM
        uses: aws-actions/setup-sam@v1
          
      - name: Install CDK
        run: |
          npm install -g aws-cdk

      - name: Use Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Run CDK Synth
        run: |
          pip install --ignore-installed -r requirements.txt
          cdk synth --no-staging > template.yaml
          
      - name: Run SAM Test
        run: |
          sam local invoke DotaDataCollectionStack/FindMatchIDsLambda -e test/na_region.json
